export const personal = [
   { name: 'first_name', id: 1, label: 'First Name', element: 'input', type: 'text', required: true },
   { name: 'last_name', id: 2, label: 'Last Name', element: 'input', type: 'text', required: true },
   { name: 'e_date', id: 3, label: 'English Date Of Birth', element: 'input', type: 'date', required: true },
   { name: 'h_date', id: 4, label: 'Hebrew Date Of Birth', element: 'input', type: 'text', required: true },
   { name: 'street_and_number', id: 5, label: 'Street And Number', element: 'input', type: 'text', required: true },
   { name: 'neighborhood', id: 6, label: 'Shchuna', element: 'input', type: 'text', required: true },
   { name: 'zip_code', id: 7, label: 'Zip Code', element: 'input', type: 'number', required: true },
   { name: 'home_number', id: 8, label: 'Home Number', element: 'input', type: 'number', required: true },
   {
      name: 'kupha_name',
      id: 9,
      label: 'Kupah',
      element: 'select',
      required: true,
      options: [
         { name: 'meuchedet', label: 'Meuchedet', id: 1 },
         { name: 'klalit', label: 'Klalit', id: 2 },
      ]
   },
   { name: 'kupha_number', id: 10, label: 'Kupha Number', element: 'input', type: 'number', required: true },
   { name: 'school', id: 11, label: 'School', element: 'input', type: 'text', required: true },
   {
      name: 'grade_finishing',
      id: 12,
      label: 'Grade Finishing',
      element: 'select',
      required: true,
      options: [
         { name: '1', label: '1', id: 1 },
         { name: '2', label: '2', id: 2 },
         { name: '3', label: '3', id: 3 },
         { name: '4', label: '4', id: 4 },
         { name: '5', label: '5', id: 5 },
         { name: '6', label: '6', id: 6 },
         { name: '7', label: '7', id: 7 },
         { name: '8', label: '8', id: 8 },
      ]
   },
   {
      name: 'grade_entering',
      id: 13,
      label: 'Grade Entering',
      element: 'select',
      required: true,
      options: [
         { name: '1', label: '1', id: 1 },
         { name: '2', label: '2', id: 2 },
         { name: '3', label: '3', id: 3 },
         { name: '4', label: '4', id: 4 },
         { name: '5', label: '5', id: 5 },
         { name: '6', label: '6', id: 6 },
         { name: '7', label: '7', id: 7 },
         { name: '8', label: '8', id: 8 },
      ]
   },
   { name: 'father_name', id: 14, label: 'Fathers Name', element: 'input', type: 'text', required: true },
   { name: 'father_phone_number', id: 15, label: 'Fathers Number', element: 'input', type: 'number', required: true },
   { name: 'mother_name', id: 16, label: 'Mothers Name', element: 'input', type: 'text', required: true },
   { name: 'mother_phone_number', id: 17, label: 'Mothers Number', element: 'input', type: 'number', required: true },
   { name: 'emergency_name', id: 18, label: 'Emergency contact', element: 'input', type: 'text', required: true },
   { name: 'emergency_phone_number', id: 19, label: 'Emergency Number', element: 'input', type: 'number', required: true },
   { name: 'email', id: 20, label: 'Email', element: 'input', type: 'email', required: true },
   { name: 'favorite_activities', id: 21, label: 'What are your childs favorite activities', element: 'textarea' },
   { name: 'dislike_activities', id: 22, label: 'Which activities does your child dislike', element: 'textarea' },
   { name: 'allergies', id: 23, label: 'Specific Metical Information (allergies etc.)', element: 'textarea' },
   { name: 'freinds', id: 24, label: 'Freinds your child whould like to be with?', element: 'textarea' },
   { name: 'enhance', id: 25, label: 'We would like your child to have a wonderful camp experience. is there any other information that we should know in order to enhance your childs summer?', element: 'textarea' },
   { name: 'signature_personal', id: 26, label: 'Signature of Parent', element: 'signature', required: true },
   { name: 'signature_date_personal', id: 27, label: 'Date', element: 'input', type: 'datetime-local', required: true },
]
